language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install -r dev-requirements.txt
    - pip install -e .

script:
    - tox

after_success:
    - codecov

notifications:
    email: false
